name: bin7r4decl
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# --------------------------------------

version: 0.0.1+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# --------------------------------------
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  #
  firebase_core: ^2.22.0
  firebase_remote_config: ^4.3.4
  webview_flutter: ^4.4.1
  retrofit: ^4.0.3
  dio: ^5.3.3
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  hive_flutter: ^1.1.0
  #
  telegram: ^0.0.3
  image_picker: ^1.0.4
  share_plus: ^7.2.1
  flutter_markdown: ^0.6.18+2
  page_view_dot_indicator: ^2.3.0
  country_currency_pickers: ^3.0.0
  #
  flutter_native_splash: ^2.3.5

# --------------------------------------

flutter_native_splash:
  android: true
  ios: true

  color: "#000000"
  image: assets/splash.jpg

  android_12:
    image: assets/splash.jpg
    icon_background_color: "#000000"

# --------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  retrofit_generator: ^8.0.3
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1


# --------------------------------------

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/certificate.pem

